### ISSUE TITLE
It does not work with ZXbaremulator

### ISSUE THREAD

**Issue by vitasam** [trilader/stm32-ps2-usb-converter#2]
Hello,
thanks for the project!

I've tested it - it works smoothly with PC or a Raspberry Pi under Raspbian OS (I noticed that the stm32 should be connected later, if it is connected before powering the RPi, the keyboard is not detected).

However I was not able to get it working with bare-metal ZX Spectrum [emulator](http://zxmini.speccy.org/en/index.html) (ZXBaremulator) on a Raspberry Pi. 

According to ZXBaremulator's author, the STM32 should declare in his HID descriptor a boot device (that's a need for Circle library). I have very little experience with USB devices, do you thinks it is doable?

**Comment by trilader** [comment]
Hi, I'm happy someone finds it useful :-)

Regarding the boot descriptor: I'm assuming that refers to the HID descriptor being boot-mode compatible. The keyboard descriptor I've implemented **should** be compatible. You can find the descriptor in [usb.c:42](https://github.com/trilader/stm32-ps2-usb-converter/blob/master/usb.c#L42).

The issue that it is not working might be that emulator initialization sequence expects the keyboard to be plugged in and ready on power on and doesn't support plugging the device in (or the device getting ready) after the system was powered up. I don't known how long the software waits before talking to the device. This might be a timing issue.

**Comment by vitasam** [comment]
You're welcome! :) 
I'm going to embed Raspberry Pi Zero W into the PS2 keyboard (the keyboard is small and looks pretty cool), so I will reuse your project there - it works pretty smooth with Raspbian OS). 

But I was now able to get it working with ZXBaremulator. The author suggested to add a parameter `usbpowerdelay=2000` in `cmdline.txt` file. It slowed down the boot by two seconds but it did not help. Even with 5 seconds ZXbaremulator can't detect the keyboard.

If you're interesting and you have RPi 2/3 at home, you can try ZXbaremulator - it is a really nice piece of retro-engineering, although the author has lost his motivation to continue its development.
